version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    # restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somelaravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  # phpmyadmin:
  #    image: phpmyadmin/phpmyadmin
  #    depends_on:
  #      - mysql
  #    links:
  #      - mysql
  #    ports:
  #      - "8081:80"
  #    environment:
  #      PMA_HOSTS: mysql
  #      PMA_USER: laravel
  #      PMA_PASSWORD: laravel

  laravel:
     image: hobord/php-fpm-laravel:dev
     # restart: always
     volumes:
       # - /c/docker/.../src:/var/www/html
       - ./:/var/www/html
     links:
       - mysql
       # - redis
     depends_on:
       - mysql
       # - redis
     environment:
       DB_HOST: mysql
       DB_PORT: 3306
       DB_DATABASE: laravel
       DB_USERNAME: laravel
       DB_PASSWORD: laravel
#       XDEBUG_CONFIG: "remote_host=192.168.99.1"
#       XDEBUG_SESSION_START: phpstorm-xdebug

  nginx_laravel:
     build:
       context: ./
       dockerfile: Dockerfile.nginx
     # restart: always
     volumes:
       # - /c/docker/.../src/public:/var/www/html/public
       - ./public:/var/www/html/public
     ports:
       - "8080:80"
     links:
       - laravel
     depends_on:
       - laravel

  # redis:
  #   image: redis

  # redis_commander:
  #   image: tenstartups/redis-commander
  #   depends_on:
  #     - redis
  #   command: --redis-host redis
  #   links:
  #     - redis:redis
  #   ports:
  #     - "8082:8081"

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodata:/data/db
  #   restart: always

  # mongoclient:
  #   image: mongoclient/mongoclient
  #   depends_on:
  #     - mongodb
  #   links:
  #     - mongodb
  #   ports:
  #     - "8083:3000"

  # elasticsearch:
  # # vim /etc/sysctl/sysctl.conf -> vm.max_map_count = 262144
  # # username and pasword-> elastic:changeme
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   environment:
  #     discovery.type: single-node

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.6.3
  #   depends_on:
  #     - elasticsearch
  #   links:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - "ELASTICSEARCH_URL=http://elasticsearch:9200"

volumes:
    db_data:
#    esdata:
#    mongodata:
